Updated compile file

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,4 +1,14 @@
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
+
+# fail fast
+set -e
+
+BUILD_DIR=$1
+CACHE_DIR=$2
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+BUILDPACK_DIR="$(dirname $(dirname $0))"
+
 echo "-----> Moving the configuration generation script into place"
-mkdir -p $BUILD_DIR/.profile.d
 cp "$BUILDPACK_DIR/bin/gen-pgpool-conf.sh" $BUILD_DIR/.profile.d/gen-pgpool-conf.sh
-chmod +x $BUILD_DIR/.profile.d/gen-pgpool-conf.sh.sh
+chmod +x $BUILD_DIR/.profile.d/gen-pgpool-conf.sh
